### PR TITLE
Update InstallKali.sh

### PR DESCRIPTION
**Pull request by roguepullrequest**
The fs download format has changed from `tar.gz` to `tar.xz`. Now it works again. :D

### CODE REVIEW

**Comment by up2smoke** [comment]
For me its not working 
IMG_20201018_223402

**Comment by roguepullrequest** [comment]
> 
> 
> For me its not working

Are you pulling from the official repo? This PR has not been merged. 
Looking at that error from gzip you don't have these changes. If you want to make the changes locally then you can run
```bash
sed -ie 's/tar.gz/tar.xz/g' InstallKali.sh
```
 Or you can download directly via wget or something to tryout the patch. 
 `https://raw.githubusercontent.com/roguepullrequest/Termux-Kali/patch-1/InstallKali.sh`

**Comment by up2smoke** [comment]
Makes No different 

IMG_20201019_001450

**Comment by roguepullrequest** [comment]
Try running `pkg upgrade` to get the latest packages into termux. Also make sure to run `for i in fs binds ; do rm -rf kali-$i ; done` ... just to be sure you have a clean working space.

**Comment by up2smoke** [comment]
Yes its works :)

**Pull request merged**
